---
- name: install haproxy on baremetal
  apt:
    name: haproxy
    state: present

- name: configure haproxy
  template:
   src: haproxy.cfg.j2
   dest: "/etc/haproxy/haproxy.cfg"

- name: restart haproxy
  systemd:
    name: haproxy
    state: restarted
    daemon_reload: yes
    enabled: yes

