---
# set the node hostname to match the inventory hostname, as long as the inventory
# host is not an IP address
- name: ensure hostname matches inventory hostname
  hostname:
    name: "{{ inventory_hostname }}"
  when: not inventory_hostname is match('(\d{1,3}\.){3}\d{1,3}')
  register: hostname
  tags: hostname

- name: ensure hostname is in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ ansible_default_ipv4.address }}.+$"
    line: "{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}"
  register: hostname
  tags: hostname

- name: enable cgroup options at boot
  copy:
    src: cmdline.txt
    dest: /boot/cmdline.txt
    owner: root
    group: root
    mode: 0755
  register: cmdline
  tags: cmdline

- name: disable swap in fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
  register: swap

- name: update all packages
  apt:
    update_cache: 'yes'
    autoclean: 'yes'
    autoremove: 'yes'
    cache_valid_time: 21600
    upgrade: 'yes'

- name: install other packages for things
  apt:
    pkg:
      - rsync

# reboot if needed
- name: reboot
  reboot:
    reboot_timeout: 120
  when: (hostname is defined and hostname.changed) or (cmdline is defined and cmdline.changed) or (swap is defined and swap.changed)
