---
# set the node hostname to match the inventory hostname, as long as the inventory
# host is not an IP address
- name: ensure hostname matches inventory hostname
  hostname:
    name: "{{ inventory_hostname }}"
  when: not inventory_hostname is match('(\d{1,3}\.){3}\d{1,3}')
  register: hostname
  tags: hostname

- name: ensure hostname is in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ ansible_default_ipv4.address }}.+$"
    line: "{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}"
  register: hostname
  tags: hostname

# reboot if needed
- name: reboot
  reboot:
    reboot_timeout: 120
  when: hostname.changed
